/**
 * Cross-language parity test. Reads vectors.json (generated by
 * scripts/gen_vectors.py from the Python reference impl) and asserts:
 *
 *   - decodeInner(inner_bytes_hex).root shape reflects the tree
 *   - encodeInner(decoded) produces byte-identical output to inner_bytes_hex
 *   - decodeEnvelope(envelope_signed_hex) returns the sig
 *   - verifySoftware(inner, sig, userSecret) == true
 *   - evalTree(tree, inputs) matches expected_output (within 1e-10)
 *   - platform countersig vector verifies
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import {
  decodeInner,
  encodeInner,
  decodeEnvelope,
  evalTree,
  signSoftware,
  verifySoftware,
  verifyPlatformCountersig,
} from "../src/index.js";

interface VectorCase {
  name: string;
  depth: number;
  input_dim: number;
  inner_bytes_hex: string;
  envelope_unsigned_hex: string;
  envelope_signed_hex: string;
  sig_hex: string;
  inputs: number[];
  expected_output: number;
}

interface CountersigCase {
  content_hash_hex: string;
  purchase_tx_id: string;
  buyer_user_id: string;
  timestamp_ns: string;
  platform_secret_hex: string;
  sig_hex: string;
}

interface VectorDoc {
  version: number;
  user_secret_hex: string;
  cases: VectorCase[];
  countersig_cases: CountersigCase[];
}

function hexToBytes(hex: string): Uint8Array {
  if (hex.length % 2 !== 0) throw new Error("bad hex length");
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return out;
}

function bytesToHex(bytes: Uint8Array): string {
  let s = "";
  for (let i = 0; i < bytes.length; i++) {
    const b = bytes[i]!;
    s += (b < 16 ? "0" : "") + b.toString(16);
  }
  return s;
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const VECTORS_PATH = resolve(__dirname, "vectors.json");
const raw = readFileSync(VECTORS_PATH, "utf-8");
const doc = JSON.parse(raw) as VectorDoc;
const userSecret = hexToBytes(doc.user_secret_hex);

for (const c of doc.cases) {
  test(`vector[${c.name}]: decode -> re-encode is byte-identical`, () => {
    const inner = hexToBytes(c.inner_bytes_hex);
    const tree = decodeInner(inner);
    assert.equal(tree.inputDim, c.input_dim);
    const reEncoded = encodeInner(tree);
    assert.equal(
      bytesToHex(reEncoded),
      c.inner_bytes_hex,
      `re-encode diverged: got=${bytesToHex(reEncoded)} want=${c.inner_bytes_hex}`,
    );
  });

  test(`vector[${c.name}]: HMAC signature matches Python`, () => {
    const inner = hexToBytes(c.inner_bytes_hex);
    const expectedSig = hexToBytes(c.sig_hex);
    const actualSig = signSoftware(inner, userSecret);
    assert.equal(
      bytesToHex(actualSig),
      c.sig_hex,
      `sig mismatch: got=${bytesToHex(actualSig)} want=${c.sig_hex}`,
    );
    assert.equal(verifySoftware(inner, expectedSig, userSecret), true);
  });

  test(`vector[${c.name}]: signed envelope decodes with sig`, () => {
    const env = hexToBytes(c.envelope_signed_hex);
    const { tree, signature } = decodeEnvelope(env);
    assert.ok(signature, "decoder should return the signature");
    assert.equal(bytesToHex(signature!), c.sig_hex);
    assert.equal(tree.inputDim, c.input_dim);
  });

  test(`vector[${c.name}]: unsigned envelope has no sig`, () => {
    const env = hexToBytes(c.envelope_unsigned_hex);
    const { tree, signature } = decodeEnvelope(env);
    assert.equal(signature, undefined);
    assert.equal(tree.inputDim, c.input_dim);
  });

  test(`vector[${c.name}]: evaluator matches Python expected_output`, () => {
    const inner = hexToBytes(c.inner_bytes_hex);
    const tree = decodeInner(inner);
    const inputs = Float64Array.from(
      c.inputs.concat(new Array(Math.max(0, tree.inputDim - c.inputs.length)).fill(0)),
    );
    const got = evalTree(tree, inputs);
    const want = c.expected_output;
    const diff = Math.abs(got - want);
    const tol = Math.max(1e-10, Math.abs(want) * 1e-10);
    assert.ok(
      diff <= tol,
      `eval diverged: got=${got} want=${want} diff=${diff} tol=${tol}`,
    );
  });
}

for (const cs of doc.countersig_cases) {
  test(`countersig vector[${cs.purchase_tx_id}]: verifies`, () => {
    const secret = hexToBytes(cs.platform_secret_hex);
    const sig = hexToBytes(cs.sig_hex);
    const ok = verifyPlatformCountersig({
      contentHashHex: cs.content_hash_hex,
      purchaseTxId: cs.purchase_tx_id,
      buyerUserId: cs.buyer_user_id,
      timestampNs: BigInt(cs.timestamp_ns),
      platformSecret: secret,
      sig,
    });
    assert.equal(ok, true);
  });
}
