"""Zero-knowledge secrets primitives (v0.16).

The capability-security layer on top of carl-studio's existing
``wallet_store`` (Fernet + PBKDF2 + keyring). Gives agents opaque
handles to sensitive values — they orchestrate workflows
(generate → copy → paste → audit) without ever seeing the raw bytes
in their own context.

Design lineage
--------------

* **Object-capability model** (Mark Miller, E-rights). Handles, not values.
* **HashiCorp Vault response wrapping.** Single-use tokens that unwrap
  privileged data. We use ``UUID`` handles the same way.
* **1Password ``op://vault/item/field`` URI shape.** Our ``SecretRef.uri``
  follows the same shape for downstream tooling compatibility.

What this module provides
-------------------------

* :class:`SecretRef` — frozen, opaque handle. No value attribute.
* :class:`SecretVault` — process-local vault keyed by ``ref_id``.
* :func:`seal` / :func:`unseal` — pynacl sealed-box helpers for
  agent-produced secrets the agent can't read back.
* Error codes under ``carl.secrets.*``:

  - ``carl.secrets.revoked`` — handle was explicitly revoked
  - ``carl.secrets.expired`` — handle's TTL elapsed
  - ``carl.secrets.unauthorized_resolve`` — resolve without privilege
  - ``carl.secrets.backend_unavailable`` — pynacl/keyring absent
  - ``carl.secrets.not_found`` — handle ref_id unknown
  - ``carl.secrets.invalid_kind`` — invalid kind on SecretRef
  - ``carl.secrets.unsupported`` — operation requires optional deps

What this module does NOT provide
---------------------------------

* Persistence. Every ``SecretVault`` is in-memory. For at-rest
  encryption, compose with ``carl_studio.wallet_store`` (Fernet).
* Platform-level clipboard or keychain. Those live in
  ``carl_studio.secrets`` to keep carl-core network-free and
  dependency-light.
* Auto-scheduled TTL revocation. Callers that want scheduled
  revocation should hook a ``threading.Timer`` in userland; the
  vault itself only checks TTL at resolve time (lazy semantics).
"""

from __future__ import annotations

import threading
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, SecretBytes

from carl_core.errors import CARLError, ValidationError
from carl_core.hashing import fingerprint


__all__ = [
    "SecretKind",
    "SecretRef",
    "SecretVault",
    "SecretsError",
    "seal",
    "unseal",
]


# ---------------------------------------------------------------------------
# Kinds — narrows what a ref claims to represent
# ---------------------------------------------------------------------------


SecretKind = Literal[
    "mint",        # freshly generated by CryptoRandomMinter (carl_studio.secrets)
    "env",         # pulled from an env var (handle → env name)
    "keychain",    # stored in OS keychain (handle → service+account)
    "vault",       # Fernet-encrypted file vault
    "clipboard",   # staged in the OS clipboard (handle → scoped write)
]
_KIND_VALUES: frozenset[str] = frozenset(
    {"mint", "env", "keychain", "vault", "clipboard"}
)


# ---------------------------------------------------------------------------
# Error taxonomy
# ---------------------------------------------------------------------------


class SecretsError(CARLError):
    """Base for all ``carl.secrets.*`` errors.

    Subclasses should set a specific ``code`` value so CLI / MCP callers
    can branch on the stable taxonomy.
    """

    code = "carl.secrets"


# ---------------------------------------------------------------------------
# SecretRef — opaque handle, never carries the value
# ---------------------------------------------------------------------------


class SecretRef(BaseModel):
    """Opaque handle to a value held somewhere the agent cannot read.

    Carry this across tool-call boundaries instead of the raw value.
    Downstream tools that need the actual bytes call :meth:`SecretVault.resolve`
    *with privilege* — the agent's context never receives the value.

    The ``uri`` follows the 1Password ``op://`` shape so external tooling
    can parse the handle without a CARL-specific SDK. The ``ref_id`` is
    a server-opaque UUID — different ``ref_id``s for otherwise-identical
    values defeat accidental deduplication attacks.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    ref_id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        description="Unique UUID for this handle. Opaque. Different refs to "
        "the same underlying value get different ref_ids.",
    )
    kind: SecretKind = Field(
        ...,
        description="What the handle refers to (mint/env/keychain/vault/clipboard).",
    )
    uri: str = Field(
        ...,
        description="1Password-shaped URI: 'carl://<vault>/<name>'. "
        "Provides a stable reference users can paste into docs / CLI "
        "without leaking the value.",
    )
    ttl_s: int | None = Field(
        default=None,
        description="Optional lifetime in seconds. None = no auto-expiry "
        "(explicit revoke required). Checked lazily at resolve time.",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When this handle was minted. Drives TTL arithmetic.",
    )

    def expired_at(self) -> datetime | None:
        """Return the absolute expiry timestamp, or None for no-TTL refs."""
        if self.ttl_s is None:
            return None
        return self.created_at + timedelta(seconds=self.ttl_s)

    def is_expired(self, *, now: datetime | None = None) -> bool:
        """Check whether the handle has passed its TTL. Always False for
        no-TTL refs. ``now`` defaults to ``datetime.now(timezone.utc)``."""
        expires = self.expired_at()
        if expires is None:
            return False
        current = now if now is not None else datetime.now(timezone.utc)
        return current >= expires

    def describe(self) -> dict[str, Any]:
        """Public metadata for logs + audit. Never contains the value."""
        expires = self.expired_at()
        return {
            "ref_id": str(self.ref_id),
            "kind": self.kind,
            "uri": self.uri,
            "ttl_s": self.ttl_s,
            "created_at": self.created_at.isoformat(),
            "expires_at": expires.isoformat() if expires is not None else None,
        }


# ---------------------------------------------------------------------------
# SecretVault — process-local, thread-safe handle KV
# ---------------------------------------------------------------------------


class _VaultEntry:
    """Internal value+metadata holder. NEVER exposed to callers."""

    __slots__ = ("secret", "fingerprint_hex", "revoked")

    def __init__(self, secret: SecretBytes, fingerprint_hex: str) -> None:
        self.secret = secret
        self.fingerprint_hex = fingerprint_hex
        self.revoked = False


class SecretVault:
    """In-memory handle → value KV with explicit resolve / revoke lifecycle.

    Thread-safe. Every operation is logged via a caller-supplied audit
    callback so the ``InteractionChain`` witnesses the handle lifecycle
    without us taking a dependency on the chain here.

    The vault:
      * Never writes to disk.
      * Stores values as :class:`pydantic.SecretBytes` (redacted in repr).
      * Returns :class:`SecretRef` on :meth:`put`; agents pass these around.
      * Requires explicit privileged :meth:`resolve` to get the bytes.
      * Emits a ``fingerprint_of`` helper so non-privileged callers can
        still reason about "is this the same value?" without reading it.
    """

    def __init__(self) -> None:
        self._entries: dict[uuid.UUID, _VaultEntry] = {}
        self._refs: dict[uuid.UUID, SecretRef] = {}
        self._lock = threading.RLock()

    # -- lifecycle -------------------------------------------------------

    def put(
        self,
        value: bytes | str,
        *,
        kind: SecretKind,
        uri: str | None = None,
        ttl_s: int | None = None,
    ) -> SecretRef:
        """Insert ``value`` into the vault. Returns a fresh :class:`SecretRef`.

        ``value`` is immediately wrapped in :class:`pydantic.SecretBytes`
        which redacts in ``repr()``. The raw bytes are still present in
        the vault's memory — callers relying on cryptographic erasure
        should not use this module alone (Python's GC makes erase-on-free
        unreliable).
        """
        if kind not in _KIND_VALUES:
            raise ValidationError(
                f"invalid secret kind: {kind!r}",
                code="carl.secrets.invalid_kind",
                context={"kind": kind, "valid": sorted(_KIND_VALUES)},
            )
        if ttl_s is not None and ttl_s < 1:
            raise ValidationError(
                f"ttl_s must be a positive int or None, got {ttl_s!r}",
                code="carl.secrets.invalid_kind",
                context={"ttl_s": ttl_s},
            )

        raw = value.encode("utf-8") if isinstance(value, str) else value
        fp = fingerprint(raw)
        ref = SecretRef(
            kind=kind,
            uri=uri or f"carl://{kind}/{uuid.uuid4().hex[:16]}",
            ttl_s=ttl_s,
        )
        entry = _VaultEntry(SecretBytes(raw), fp)

        with self._lock:
            self._entries[ref.ref_id] = entry
            self._refs[ref.ref_id] = ref

        return ref

    def resolve(self, ref: SecretRef, *, privileged: bool = False) -> bytes:
        """Dereference a handle to its raw bytes.

        ``privileged=True`` gate is a coarse, explicit marker. It does
        NOT provide cryptographic enforcement — any Python caller can
        pass ``privileged=True``. Its purpose is to force callers to
        visibly opt into the de-reference at each call site so reviewers
        spot every value-access in a diff.

        Non-privileged callers receive :class:`SecretsError` with code
        ``carl.secrets.unauthorized_resolve``.
        """
        if not privileged:
            raise SecretsError(
                "SecretVault.resolve() requires privileged=True. "
                "Non-privileged callers should use fingerprint_of() or "
                "delegate resolution to a tool that explicitly opts in.",
                code="carl.secrets.unauthorized_resolve",
                context={"ref_id": str(ref.ref_id), "kind": ref.kind},
            )

        with self._lock:
            entry = self._entries.get(ref.ref_id)
            if entry is None:
                raise SecretsError(
                    f"unknown secret handle: {ref.ref_id}",
                    code="carl.secrets.not_found",
                    context={"ref_id": str(ref.ref_id)},
                )
            if entry.revoked:
                raise SecretsError(
                    f"secret handle {ref.ref_id} was revoked",
                    code="carl.secrets.revoked",
                    context={"ref_id": str(ref.ref_id)},
                )
            if ref.is_expired():
                # Self-expire at first access for housekeeping.
                entry.revoked = True
                raise SecretsError(
                    f"secret handle {ref.ref_id} has expired",
                    code="carl.secrets.expired",
                    context={
                        "ref_id": str(ref.ref_id),
                        "created_at": ref.created_at.isoformat(),
                        "ttl_s": ref.ttl_s,
                    },
                )
            return entry.secret.get_secret_value()

    def revoke(self, ref: SecretRef) -> bool:
        """Invalidate a handle. Returns True iff the handle existed + was live.

        Idempotent: revoking an already-revoked or unknown handle returns
        False without raising. The revoked entry's bytes remain in memory
        until GC; callers wanting stricter erasure must zero the buffer
        themselves (Python doesn't expose a reliable primitive for this).
        """
        with self._lock:
            entry = self._entries.get(ref.ref_id)
            if entry is None or entry.revoked:
                return False
            entry.revoked = True
        return True

    def fingerprint_of(self, ref: SecretRef) -> str:
        """Return the 12-hex sha256 prefix of the referenced value.

        Safe to log / show to the agent / embed in an `InteractionChain`
        Step. Non-privileged: does NOT require ``privileged=True``.
        """
        with self._lock:
            entry = self._entries.get(ref.ref_id)
            if entry is None:
                raise SecretsError(
                    f"unknown secret handle: {ref.ref_id}",
                    code="carl.secrets.not_found",
                    context={"ref_id": str(ref.ref_id)},
                )
            # Revoked handles still have a stable fingerprint — callers may
            # want to audit "which secret was revoked" without re-minting.
            return entry.fingerprint_hex

    def exists(self, ref: SecretRef) -> bool:
        """Truthy iff the handle is known + not revoked + not expired.

        Non-privileged cheap check the agent can use to branch.
        """
        with self._lock:
            entry = self._entries.get(ref.ref_id)
            if entry is None or entry.revoked:
                return False
        return not ref.is_expired()

    def list_refs(self) -> list[SecretRef]:
        """Enumerate non-revoked, non-expired handles in the vault.

        Metadata-only — the returned list contains opaque :class:`SecretRef`
        objects whose ``.describe()`` exposes kind/uri/ttl/timestamps but
        never the value.
        """
        now = datetime.now(timezone.utc)
        with self._lock:
            refs: list[SecretRef] = []
            for ref_id, ref in self._refs.items():
                entry = self._entries.get(ref_id)
                if entry is None or entry.revoked:
                    continue
                if ref.is_expired(now=now):
                    continue
                refs.append(ref)
            return refs

    def __len__(self) -> int:
        with self._lock:
            return sum(
                1
                for ref_id, ref in self._refs.items()
                if (entry := self._entries.get(ref_id)) is not None
                and not entry.revoked
                and not ref.is_expired()
            )


# ---------------------------------------------------------------------------
# Sealed-box helpers (pynacl)
# ---------------------------------------------------------------------------
#
# Asymmetric one-way encryption: the agent gets a recipient pubkey, seals a
# value with it, and emits the ciphertext. The agent cannot read the value
# back — only the holder of the private key (typically the user, stored in
# OS keychain) can unseal. This is the right primitive for "agent mints a
# secret the user is meant to receive"; use when you want the agent to
# operate upstream of the user and not retain read access to its own output.


def seal(pubkey: bytes, value: bytes) -> bytes:
    """Seal ``value`` to ``pubkey`` using NaCl ``SealedBox``.

    ``pubkey`` is a raw 32-byte Curve25519 public key. Returns the sealed
    ciphertext (48-byte header + value ciphertext). Requires ``pynacl``.
    Raises :class:`SecretsError` ``carl.secrets.backend_unavailable`` if
    pynacl is not importable.
    """
    try:
        from nacl.public import PublicKey, SealedBox
    except ImportError as exc:  # pragma: no cover - exercised in env-check test
        raise SecretsError(
            "pynacl is required for seal/unseal. Install with: "
            "pip install 'carl-studio[secrets]'",
            code="carl.secrets.backend_unavailable",
            context={"missing": "pynacl"},
            cause=exc,
        ) from exc
    if len(pubkey) != 32:
        raise ValidationError(
            "pubkey must be exactly 32 bytes (Curve25519)",
            code="carl.secrets.invalid_kind",
            context={"got_len": len(pubkey)},
        )
    box = SealedBox(PublicKey(pubkey))
    return bytes(box.encrypt(value))


def unseal(privkey: bytes, ciphertext: bytes) -> bytes:
    """Inverse of :func:`seal`.

    ``privkey`` is a raw 32-byte Curve25519 private key (typically loaded
    from the OS keychain via ``carl_studio.secrets.KeychainBackend``).
    Returns the plaintext bytes.
    """
    try:
        from nacl.public import PrivateKey, SealedBox
    except ImportError as exc:  # pragma: no cover
        raise SecretsError(
            "pynacl is required for seal/unseal. Install with: "
            "pip install 'carl-studio[secrets]'",
            code="carl.secrets.backend_unavailable",
            context={"missing": "pynacl"},
            cause=exc,
        ) from exc
    if len(privkey) != 32:
        raise ValidationError(
            "privkey must be exactly 32 bytes (Curve25519)",
            code="carl.secrets.invalid_kind",
            context={"got_len": len(privkey)},
        )
    box = SealedBox(PrivateKey(privkey))
    return bytes(box.decrypt(ciphertext))


# ---------------------------------------------------------------------------
# Convenience: generate a keypair without round-tripping through bytes
# ---------------------------------------------------------------------------
#
# Not a primary export — kept deliberately thin. Callers that need an
# ed25519 signing pair should reach for carl_core.signing; Curve25519
# box keys (for seal/unseal) live here because the consumer of sealed
# ciphertext is the vault, not the signer.


def generate_box_keypair() -> tuple[bytes, bytes]:
    """Generate a fresh Curve25519 (privkey, pubkey) for sealed-box use.

    Both halves are raw 32-byte values. The caller is responsible for
    storing the private half somewhere safe (OS keychain, Fernet vault).
    Requires pynacl.
    """
    try:
        from nacl.public import PrivateKey
    except ImportError as exc:  # pragma: no cover
        raise SecretsError(
            "pynacl is required for keypair generation. Install with: "
            "pip install 'carl-studio[secrets]'",
            code="carl.secrets.backend_unavailable",
            context={"missing": "pynacl"},
            cause=exc,
        ) from exc
    priv = PrivateKey.generate()
    # ``bytes(key)`` gives the raw 32-byte form for both halves.
    return bytes(priv), bytes(priv.public_key)


__all__ += ["generate_box_keypair"]
