"""Render EnvState → training-config YAML + summary dict.

Writes a YAML suitable for ``carl train --config carl.yaml``. Missing
fields render as YAML ``null`` with a TODO comment so the user can
edit by hand rather than facing a cryptic validation error later.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from carl_studio.env_setup.state import EnvState


def _enum_value(v: Any) -> Any:
    """Unwrap an Enum to its underlying value for YAML/JSON output.

    Carl's str-Enums compare equal to their string values, but f-string
    interpolation renders as ``Mode.TRAIN`` rather than ``train``. This
    helper keeps the output plain-string without forcing every call site
    to call ``.value`` explicitly.
    """
    if isinstance(v, Enum):
        return v.value
    return v


def render_training_config_yaml(state: EnvState) -> str:
    """Emit a YAML string ready to drop in ``carl.yaml``.

    Deterministic: same state → same string (sorted keys, stable
    format). Writes a header comment with generation timestamp + the
    env-setup invocation that produced it.
    """

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = [
        "# Generated by `carl env` — progressive-disclosure wizard",
        f"# Generated at: {ts}",
        "# Edit this file by hand or re-run `carl env` to regenerate.",
        "",
    ]

    def _emit(key: str, value: Any, comment: str | None = None) -> None:
        unwrapped = _enum_value(value)
        if unwrapped is None:
            lines.append(f"{key}: null  # TODO: set {comment or key}")
        elif isinstance(unwrapped, str):
            lines.append(f"{key}: {_quote_if_needed(unwrapped)}")
        else:
            lines.append(f"{key}: {unwrapped}")

    # Top-level shape matches `carl_studio.types.config.TrainingConfig`.
    _emit("mode", state.mode)
    _emit("method", state.method)
    _emit("base_model", state.base_model, comment="HF model id (e.g. meta-llama/Llama-3.2-1B)")
    _emit("dataset", state.dataset)
    _emit("dataset_kind", state.dataset_kind)
    _emit("compute", state.compute)

    lines.append("")
    lines.append("# Sensible defaults; override as needed:")
    lines.append("num_train_epochs: 1")
    lines.append("per_device_train_batch_size: 4")
    lines.append("gradient_accumulation_steps: 4")
    lines.append("learning_rate: 2.0e-5")
    lines.append("warmup_ratio: 0.03")

    if state.method in ("grpo", "cascade"):
        lines.append("")
        lines.append("# GRPO-specific:")
        lines.append("num_generations: 8")
        lines.append("beta: 0.04")
        reward_class = _reward_class_for(state.reward)
        lines.append(f"reward_class: {reward_class}")

    if state.method == "cascade" and state.cascade_stages is not None:
        lines.append("")
        lines.append(f"cascade_stages: {state.cascade_stages}")

    if state.eval_gate and state.eval_gate != "none":
        lines.append("")
        lines.append(f"eval_gate: {_enum_value(state.eval_gate)}")

    return "\n".join(lines) + "\n"


def _reward_class_for(reward: str | None) -> str:
    """Map the 4-value question answer to a concrete reward_class string."""
    if reward == "phase_adaptive":
        return "phase_adaptive  # Kuramoto-R-weighted CARL composite"
    if reward == "custom":
        return "custom  # TODO: plug in your own reward fn"
    if reward == "none":
        return "null  # TODO: none → pure supervised loss, method should be sft"
    # default / "static" → the canonical composite
    return "composite  # 50% coherence + 30% format + 20% discontinuity"


def render_summary_dict(state: EnvState) -> dict[str, Any]:
    """Structured summary for JSON output or programmatic consumption."""
    return {
        "mode": state.mode,
        "method": state.method,
        "dataset": state.dataset,
        "dataset_kind": state.dataset_kind,
        "compute": state.compute,
        "base_model": state.base_model,
        "complete": state.is_complete,
    }


def _quote_if_needed(value: str) -> str:
    """Quote YAML string when it contains reserved characters."""
    if any(ch in value for ch in (":", "#", "[", "]", "{", "}")) or value != value.strip():
        escaped = value.replace('"', '\\"')
        return f'"{escaped}"'
    return value


__all__ = ["render_training_config_yaml", "render_summary_dict"]
