"""HuggingFace Hub integration with coherence metadata."""

from __future__ import annotations

from pathlib import Path

from carl_studio import __version__
from carl_studio.primitives.constants import KAPPA, SIGMA


def generate_model_card(
    model_id: str,
    base_model: str,
    method: str,
    dataset: str,
    phi_mean: float = 0.0,
    cloud_quality: float = 0.0,
    discontinuity_density: float = 0.0,
    coherence_health: str = "healthy",
    training_steps: int = 0,
) -> str:
    """Generate a model card with coherence metadata."""
    return f"""---
library_name: transformers
base_model: {base_model}
tags:
  - carl-studio
  - coherence-aware-rl
  - {method}
---

# {model_id}

Trained with [CARL Studio](https://github.com/terminals-tech/carl-studio) — Coherence-Aware Reinforcement Learning.

## Training

- **Base model**: [{base_model}](https://huggingface.co/{base_model})
- **Method**: {method.upper()}
- **Dataset**: [{dataset}](https://huggingface.co/datasets/{dataset})
- **Steps**: {training_steps}

## Coherence Metrics

| Metric | Value |
|--------|-------|
| Order Parameter (Φ) | {phi_mean:.4f} |
| Cloud Quality | {cloud_quality:.4f} |
| Discontinuity Density | {discontinuity_density:.4f} |
| Coherence Health | {coherence_health} |

## Conservation Law

| Constant | Value |
|----------|-------|
| κ (kappa) | {KAPPA:.6f} |
| σ (sigma) | {SIGMA:.6f} |
| κ × σ | {KAPPA * SIGMA:.1f} |

---

*Generated by CARL Studio v{__version__} — Intuition Labs LLC*
"""


async def push_with_metadata(
    model_path: str,
    repo_id: str,
    base_model: str,
    method: str,
    dataset: str,
    coherence_metrics: dict | None = None,
    private: bool = False,
) -> str:
    """Push a model to HuggingFace Hub with coherence metadata in the model card.

    Returns the Hub URL.
    """
    from huggingface_hub import HfApi, get_token

    path = Path(model_path)
    if not path.exists():
        raise FileNotFoundError(f"Model path not found: {model_path}")

    api = HfApi(token=get_token())

    # Create or get repo
    api.create_repo(repo_id, exist_ok=True, private=private)

    # Upload model artifacts first.
    if path.is_dir():
        api.upload_folder(
            folder_path=str(path),
            repo_id=repo_id,
            commit_message="Upload model artifacts from CARL Studio",
            ignore_patterns=["**/__pycache__/**", ".DS_Store"],
        )
    else:
        api.upload_file(
            path_or_fileobj=str(path),
            path_in_repo=path.name,
            repo_id=repo_id,
            commit_message="Upload model artifact from CARL Studio",
        )

    # Generate model card
    metrics = coherence_metrics or {}
    card = generate_model_card(
        model_id=repo_id,
        base_model=base_model,
        method=method,
        dataset=dataset,
        phi_mean=metrics.get("phi_mean", 0.0),
        cloud_quality=metrics.get("cloud_quality", 0.0),
        discontinuity_density=metrics.get("discontinuity_density", 0.0),
        coherence_health=metrics.get("coherence_health", "healthy"),
        training_steps=metrics.get("training_steps", 0),
    )

    # Upload model card
    api.upload_file(
        path_or_fileobj=card.encode(),
        path_in_repo="README.md",
        repo_id=repo_id,
        commit_message="Add CARL Studio coherence metadata",
    )

    return f"https://huggingface.co/{repo_id}"
